version: '3.7'
services:
  db:
    image: mysql:latest 
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/dump:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fastservice
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  backend:
    container_name: fastservice-backend
    build:
      context: ./api/src/main/resources/
      dockerfile: Dockerfile
    volumes:
      - ./api/:/backend
    ports:
    - '8080:8080'
    restart: always
    working_dir: /backend
    depends_on:
      - db
  frontend:
    container_name: fastservice-frontend
    build:
      context: ./web/
      dockerfile: Dockerfile
    volumes:
      - './web/:/appfront'
      - '/appfront/node_modules'
    ports:
      - '8082:8080'
    restart: always
    environment:
      - NODE_ENV=development